---
title: "SIRD"
output: pdf_document
date: "2025-12-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```







```{r}
d10  <- density(inf10$infected)
d50  <- density(inf50$infected)
d100 <- density(inf100$infected)

# Find global x-range
xmin <- min(d10$x, d50$x, d100$x)
xmax <- max(d10$x, d50$x, d100$x)

# Empty plot with fixed x-range
plot(0,0,type="n",
     xlim=c(xmin, xmax),
     ylim=c(0, max(d10$y, d50$y, d100$y)),
     xlab="Infected", ylab="Density",
     main="Infected Population Density at t = 10, 50, 100")

lines(d10,  lwd=2, col="blue")
lines(d50,  lwd=2, col="red")
lines(d100, lwd=2, col="darkgreen")

legend("topright",
       legend=c("t = 10","t = 50","t = 100"),
       col=c("blue","red","darkgreen"),
       lwd=2)

```
```{r}
library(tidyverse)


inf10  <- read.csv("C:/Users/rober/Downloads/infected_t10.csv", header=FALSE)%>% mutate(time="10")
inf50  <- read.csv("C:/Users/rober/Downloads/infected_t50.csv", header=FALSE) %>% mutate(time="50")
inf100 <- read.csv("C:/Users/rober/Downloads/infected_t100.csv", header=FALSE)%>% mutate(time="100")


colnames(inf10)[1]  <- "infected"
colnames(inf50)[1]  <- "infected"
colnames(inf100)[1] <- "infected"

# Combine
df <- bind_rows(inf10, inf50, inf100)

# Plot
ggplot(df, aes(x = infected, color = time, fill = time)) +
  geom_density(alpha = 0.35, linewidth = 1.2) +
  scale_color_manual(values = c("10"="blue", "50"="red", "100"="darkgreen")) +
  scale_fill_manual(values = c("10"="blue", "50"="red", "100"="darkgreen")) +
  theme_minimal(base_size = 14) +
  labs(
    title = "Density of Infected Population at t = 10, 50, and 100",
    x = "Infected",
    y = "Density",
    color = "Time",
    fill = "Time"
  )

```

```{r}



inf10  <- read.csv("C:/Users/rober/Downloads/infected_t10.csv", header=FALSE)%>% mutate(time="10")
inf50  <- read.csv("C:/Users/rober/Downloads/infected_t50.csv", header=FALSE) %>% mutate(time="50")
inf100 <- read.csv("C:/Users/rober/Downloads/infected_t100.csv", header=FALSE)%>% mutate(time="100")


colnames(inf10)[1]  <- "infected"
colnames(inf50)[1]  <- "infected"
colnames(inf100)[1] <- "infected"

# Combine
df <- bind_rows(inf10, inf50, inf100)

# Plot overlaid histograms
ggplot(df, aes(x = infected, fill = time, color = time)) +
  geom_histogram(
    position = "identity",
    bins = 30,
    alpha = 0.35,
    linewidth = 0.5
  ) +
  scale_fill_manual(values = c("10"="blue", "50"="red", "100"="darkgreen")) +
  scale_color_manual(values = c("10"="blue", "50"="red", "100"="darkgreen")) +
  theme_minimal(base_size = 14) +
  labs(
    title = "Histogram of Infected Population at t = 10, 50, and 100",
    x = "Infected",
    y = "Count",
    fill = "Time",
    color = "Time"
  )

```

